#!/bin/sh
echo ""
echo "Enter root password to install xhomer as suid root"
echo ""
echo "(This is necessary only to run in DGA mode or to access certain"
echo "hardware devices in the host echo operating system)"
echo ""
su -c "chown root.root xhomer xhomer.static texthomer texthomer.static >&/dev/null ; chmod +s xhomer xhomer.static texthomer texthomer.static >&/dev/null"
