#!/bin/bash

/* patchkernels: Patch multiple 2.9 BSD kernels

   Copyright (c) 1997-2024, Tarik Isani (xhomer@isani.org)

   This file is part of Xhomer.

   Xhomer is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License version 2 
   as published by the Free Software Foundation.

   Xhomer is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Xhomer; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/


./patch_kernel rd50 153 4 16 70 30
./patch_kernel rd51 306 4 16 70 30
./patch_kernel rd31 615 4 16 70 30
./patch_kernel rd52 512 8 16 70 30
./patch_kernel rd32 820 6 16 70 30
./patch_kernel rd53 1024 8 16 70 30
./patch_kernel 128m 1024 8 32 70 30
